### ISSUE TITLE
Передача товаров для Робочек

### ISSUE THREAD

**Issue by robotE13** [yii-cms/yii2-robokassa#14]
Ну собственно вопрос в названии и заключается. Как нибудь корзину то для фискализации можно передать?

**Comment by gonimar** [comment]
Хм, думаю это выходит за рамки этого компонента.
Нужно посмотреть.

**Comment by robotE13** [comment]
Да я глянул уже. Не прикрутить никак. Видел форк где просто отдельная функция payment2() написана в которую можно одним из параметров корзину передать.
