### ISSUE TITLE
В методе checkSignature и в остальных частях кода тоже убрать надо доп. параметры в проверку подписи?

### ISSUE THREAD

**Issue by yakovlef** [yii-cms/yii2-robokassa#18]
При текущем варианте если передать параметр то не сработает успешный экшен поидее. Потому что при передаче подпись будет одной, а с параметром уже другой?

**Comment by gonimar** [comment]
Вроде так и должно, по документации, https://docs.robokassa.ru/#1261

**Comment by gonimar** [comment]
Есть возможность проверить? что прилетает от них?

**Comment by yakovlef** [comment]
Да, только смогу на днях, сейчас перед запуском проекта все тестирую

**Comment by yakovlef** [comment]
Так там получается просто надо убрать те же доп параметры в подписи и все. Могу сделать пулл?

**Comment by gonimar** [comment]
В документации написано что они учавствуют

**Comment by gonimar** [comment]
> База для расчёта контрольной суммы: OutSum:InvId:Пароль#1 – если Вы не передавали пользовательские параметры, и: OutSum:InvId:Пароль#1:[Пользовательские параметры].

**Comment by yakovlef** [comment]
Да увидел, перепроверю у себя, так как у меня ломается оплата если я передаю параметры

**Comment by gonimar** [comment]
Ок, спасибо

**Comment by yakovlef** [comment]
В общем вот как, передача параметра IncCurrLabel не должна проходить через "доп. параметры" и соответственно IncCurrLabel не должен принимать участии при вычислении signature

Надо как-то вынести чтобы при формировании линка можно было еще установить например IncCurrLabel

**Comment by yakovlef** [comment]
Тут чуть ниже идет пример с списком всех параметров

https://docs.robokassa.ru/#1232

**Comment by gonimar** [comment]
> Надо как-то вынести чтобы при формировании линка можно было еще установить например IncCurrLabel

Но ведь его можно передать https://github.com/yii-cms/yii2-robokassa/blob/master/Merchant.php#L50

А при успешном выполнении `SuccessAction` я думаю это все можно получить из `$_REQUEST`

**Comment by yakovlef** [comment]
Да, тогда теперь остается вернуть изначальную проверку на доп. параметры в подпись и будет готово

Я бы сделал этот параметр на уровне конфигурации компонента, так как платеж обычно делают на весь проект по единому формату. Типо public $IncCurrLabel;

**Comment by gonimar** [comment]
т.е. пользовательские параметры все таки должны участвовать?

`IncCurrLabel` может зависеть от страны например, лучше оставить так

**Comment by yakovlef** [comment]
Оказывается да.

База для расчёта контрольной суммы: OutSum:InvId:Пароль#1 – если Вы не передавали пользовательские параметры, и: OutSum:InvId:Пароль#1:[Пользовательские параметры].

Например: если Вы передали нам параметры с вот такими значениями:

    OutSum = 100.26
    InvId = 450009
    Shp_login = Vasya
    Shp_oplata = 1

– то база для расчёта контрольной суммы будет выглядеть так: 100.26:450009:Пароль#1:Shp_login=Vasya:Shp_oplata=1.

**Comment by gonimar** [comment]
обновил, проверь

**Comment by yakovlef** [comment]
Вроде работает, сам платеж еще не делал, но так все формирует. Спасибо!

А IncCurrLabel и раньше был в параметрах? Я его получается не видел? :)

**Comment by gonimar** [comment]
Получается)
