### ISSUE TITLE
Вопрос о версиях

### ISSUE THREAD

**Issue by c7v** [yii-cms/yii2-robokassa#30]
В README.md указана установка любой версии начиная со второй
```
composer require yii-cms/yii2-robokassa:2.*
```
Но в релизах https://github.com/yii-cms/yii2-robokassa/releases последняя версия 1.3.1. Либо в README.md ошибка и нужно исправить с yii2-robokassa:2.* на yii2-robokassa:1.* либо я что-то не понял, прошу тогда разъяснить, где вторая версия.

Автору спасибо за код.

**Comment by gonimar** [comment]
Это заделка на новую версию по которой велась разработка в ветке мастер, по добавлению фискализации. Если выбрать тэг последней версии будет актуальный README.md для выбранной версии.

В настоящий момент в ветке мастер код не достаточно тестировался. Его можно подтянуть указав вместо версии ветку yii2-robokassa:dev-master

Буду признателен если потестируете код из ветки мастер.

Были планы увеличить мажорную версию, так как были крупные изменения ломающие обратную совместимость.

**Comment by c7v** [comment]
Спасибо за ответ и объяснения по версиям. С удовольствием приму участие по тестированию.
