### ISSUE TITLE
Models? Views? as example?

### ISSUE THREAD

**Issue by m1roff** [yii-cms/yii2-robokassa#8]
А где модель? вьюхи? (хотя бы как пример)

**Comment by gonimar** [comment]
Вьюхи и модель чего? Пример чего нужен?

Это просто клиент на апи робокассы, пример формы оплаты вроде как тут не к месту.

Можно приложение разве что запилить для примера использования. Если оно того стоит.

**Comment by m1roff** [comment]
Пол года прошло, уже забыто
